import Header from "@/components/sections/Header"
import "../styles/globals.css"
import { Metadata } from "next"
import Footer from "@/components/sections/Footer"

export const metadata: Metadata = {
	title: "Skyline",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="ja" className="h-full">

			<body className="bg-gray-100 h-full">
				
				<Header />

				<main className="xl:w-[1200px] px-4 xl:px-0 mx-auto">
					{children}
				</main>

				<Footer className="mt-24 sticky top-full" />
			</body>
		</html>
	)
}
