import Header from "@/components/sections/Header"
import "../styles/globals.css"
import { Metadata } from "next"
import Footer from "@/components/sections/Footer"

export const metadata: Metadata = {
	title: "Skyline",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="ja">

			<body className="bg-gray-100">
				
				<Header />

				<main className="lg:w-[1024px] px-4 lg:px-0 mx-auto">
					{children}
				</main>

				<Footer className="mt-24" />
			</body>
		</html>
	)
}
